### ISSUE TITLE
zmq.error.ZMQError: Socket operation on non-socket

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-uiserver#115]
**Describe the bug**

After testing the complex workflow for a while, I was about to shutdown everything and go home, then noticed this strange exception.

Reporting in case others see it, or if anybody has any idea what could cause it, how to fix, etc.

**Release version(s) and/or repository branch(es) affected?**

`master`

**Steps to reproduce the bug**

Not quite sure... I was just running the complex workflow for +10minutes. There were the normal coroutine errors (#108), but this one is new to me.

**Expected behavior**

No errors :grimacing: 

**Screenshots**

![image](https://user-images.githubusercontent.com/304786/73417450-014cba00-437d-11ea-8b63-e1d52159b50e.png)

**Additional context**

Exception:

```
16:07:33.755 [ConfigProxy] info: 200 GET /api/routes 
[I 2020-01-30T16:07:33.773 JupyterHub proxy:319] Checking routes
16:12:33.764 [ConfigProxy] info: 200 GET /api/routes 
[I 2020-01-30T16:12:33.780 JupyterHub proxy:319] Checking routes
2020-01-30 16:14:11,661 tornado.application ERROR    Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f92a17365f8>>, <Task finished coro=<WorkflowsManager.gather_workflows() done, defined at /home/kinow/Development/python/workspace/cylc-uiserver/cylc/uiserver/workflows_mgr.py:112> exception=ZMQError('Socket operation on non-socket')>)
Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/home/kinow/Development/python/workspace/cylc-uiserver/cylc/uiserver/workflows_mgr.py", line 166, in gather_workflows
    await asyncio.gather(*gathers)
  File "/home/kinow/Development/python/workspace/cylc-uiserver/cylc/uiserver/data_store_mgr.py", line 87, in sync_workflow
    await self.entire_workflow_update(ids=[w_id])
  File "/home/kinow/Development/python/workspace/cylc-uiserver/cylc/uiserver/data_store_mgr.py", line 231, in entire_workflow_update
    items = await asyncio.gather(*gathers)
  File "/home/kinow/Development/python/workspace/cylc-uiserver/cylc/uiserver/workflows_mgr.py", line 64, in workflow_request
    result = await client.async_request(command, args, timeout)
  File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.7/site-packages/cylc/flow/network/client.py", line 171, in async_request
    res = await self.socket.recv()
  File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.7/site-packages/zmq/_future.py", line 185, in recv
    dict(flags=flags, copy=copy, track=track)
  File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.7/site-packages/zmq/_future.py", line 332, in _add_recv_event
    timeout_ms = self._shadow_sock.rcvtimeo
  File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.7/site-packages/zmq/sugar/attrsettr.py", line 48, in __getattr__
    return self._get_attr_opt(upper_key, opt)
  File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.7/site-packages/zmq/sugar/attrsettr.py", line 52, in _get_attr_opt
    return self.get(opt)
  File "zmq/backend/cython/socket.pyx", line 501, in zmq.backend.cython.socket.Socket.get
  File "zmq/backend/cython/socket.pyx", line 262, in zmq.backend.cython.socket._getsockopt
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Socket operation on non-socket
16:17:33.748 [ConfigProxy] info: 200 GET /api/routes 
[I 2020-01-30T16:17:33.764 JupyterHub proxy:319] Checking routes

```

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by kinow** [comment]
Haven't seen this one since I reported it. Will close. We can search here if that happens again :+1:
