### ISSUE TITLE
Crashed flows cause traceback

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-uiserver#136]
If flows are killed (as opposed to shutting down cleanly) they can sometimes leave behind the contact file which makes them appear (from the filesystem) to be running.

At the moment when the UIServer attempts to contact these flows we get traceback.

```
cylc.flow.exceptions.SuiteStopped: <flow-name> is not running
```

The flows appear in the UI as running.

**Comment by hjoliver** [comment]
(Need to check if this is still the case)

**Comment by wxtim** [comment]
I've tried this and can't replicate it: 
I tried copying a contact file out, stopping the workflow and then restoring it.

**Comment by oliver-sanders** [comment]
I managed to replicate it:

```
[E 2022-02-01 10:12:53.863 ServerApp] Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f0e8c66fdd0>>, <Task finished coro=<WorkflowsManager.update() done, defined at ~/cylc-uiserver/cylc/uiserver/workflows_mgr.py:219> exception=ClientError("Failed to find user's private key, so cannot connect.")>)
    Traceback (most recent call last):
      File "~/cylc-flow/cylc/flow/network/__init__.py", line 263, in _socket_connect
        client_priv_key_info.full_key_path)
      File "~/mambaforge/envs/cylc-8.0rc1.dev/lib/python3.7/site-packages/zmq/auth/certs.py", line 98, in load_certificate
        raise IOError("Invalid certificate file: {0}".format(filename))
    OSError: Invalid certificate file: ~/cylc-run/one/.service/client.key_secret
       
    During handling of the above exception, another exception occurred:
       
    Traceback (most recent call last):
      File "~/mambaforge/envs/cylc-8.0rc1.dev/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
        ret = callback()
      File "~/mambafoorge/envs/cylc-8.0rc1.dev/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
        future.result()
      File "~/cylc-uiserver/cylc/uiserver/workflows_mgr.py", line 253, in update
        await self._connect(wid, flow)
      File "~/cylc-uiserver/cylc/uiserver/workflows_mgr.py", line 192, in _connect
        flow['req_client'] = WorkflowRuntimeClient(flow['name'])
      File "~/cylc-flow/cylc/flow/network/client.py", line 145, in __init__
        self.start(self.host, self.port, srv_public_key_loc)
      File "~/cylc-flow/cylc/flow/network/__init__.py", line 153, in start
        self._start_sequence(*args, **kwargs)                                              File "~/cylc-flow/cylc/flow/network/__init__.py", line 167, in _start_sequence
        self._socket_connect(*args, **kwargs)
      File "~/cylc-flow/cylc/flow/network/__init__.py", line 265, in _socket_connect
        raise ClientError(error_msg)
    cylc.flow.exceptions.ClientError: Failed to find user's private key, so cannot connect.
```

I get the same traceback when I restore the contact file *then* start the GUI as I do when I restore the contact file *whilst* this GUI is still running (after the scan interval has passed).

**Comment by oliver-sanders** [comment]
(I'll take a look at the code whilst I'm here)
