### ISSUE TITLE
Test setup.py and setuptools

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-uiserver#17]
`pip install -e .` works fine, but in a Centos6 container with Anaconda 3.7, after `pip install .` (not editable), got the following error:

```
bash-4.1# cylc-singleuser 
Traceback (most recent call last):
  File "/opt/anaconda3/bin/cylc-singleuser", line 6, in <module>
    from cylc_singleuser import main
  File "/opt/anaconda3/lib/python3.7/site-packages/cylc_singleuser.py", line 11, in <module>
    from handlers import *
ModuleNotFoundError: No module named 'handlers'
```

The container is a bit of a monster as it's only a test for #15 . But reporting this issue just in case.

**Comment by kinow** [comment]
Confirmed the bug. I can `import cylc_singleuser`, but `cylc-singleuser` fails after installing with `pip install .`.
