### ISSUE TITLE
"Cannot return null for non-nullable field Workflow.id" when stopping multiple workflows

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-uiserver#247]
**Describe the bug**

Noted the UI ended up in a very weird state, with workflows replacing each other in an array :dizzy_face: Couldn't understand what's going on (still debugging it), but noticed an error in the UIS. Can't tell whether related or not, couldn't capture the deltas involved.

**Release version(s) and/or repository branch(es) affected?**

`master`

**Steps to reproduce the bug**

1. Install a workflow 4 or more times
2. Start all workflows
3. Let it run for a while, looking at the UI (maybe TUI works too?)
4. Stop one workflow after the other, in a short (1, 2 seconds) interval. \
5. Observe UIS logs, look for:

```bash
[I 2021-09-13T16:01:17.483 JupyterHub log:189] 200 POST /hub/api/users/kinow/activity (kinow@127.0.0.1) 22.90ms
[D 2021-09-13 16:03:58.581 CylcUIServer] stop_workflow(kinow|one/two/three/run1)
[D 2021-09-13 16:03:58.582 CylcUIServer] purge_workflow(kinow|one/two/three/run1)
ERROR:graphql.execution.utils:Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.8/site-packages/promise/promise.py", line 87, in try_catch
    return (handler(*args, **kwargs), None)
  File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.8/site-packages/graphql/execution/executor.py", line 531, in <lambda>
    lambda resolved: complete_value(
  File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.8/site-packages/graphql/execution/executor.py", line 571, in complete_value
    return complete_object_value(
  File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.8/site-packages/graphql/execution/executor.py", line 722, in complete_object_value
    return execute_fields(  # type: ignore
  File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.8/site-packages/graphql/execution/executor.py", line 244, in execute_fields
    result = resolve_field(
  File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.8/site-packages/graphql/execution/executor.py", line 367, in resolve_field
    return complete_value_catching_error(
  File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.8/site-packages/graphql/execution/executor.py", line 475, in complete_value_catching_error
    return complete_value(exe_context, return_type, field_asts, info, path, result)
  File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.8/site-packages/graphql/execution/executor.py", line 546, in complete_value
    return complete_nonnull_value(
  File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.8/site-packages/graphql/execution/executor.py", line 743, in complete_nonnull_value
    raise GraphQLError(
graphql.error.base.GraphQLError: Cannot return null for non-nullable field Workflow.id.

```

**Expected behavior**

No tracebacks :tada: 

**Screenshots**

![image](https://user-images.githubusercontent.com/304786/133023102-e72b2b9a-a19b-4e4c-bd76-b353f23ad76b.png)

**Additional context**

FWIW, I am working on https://github.com/cylc/cylc-ui/issues/721. But I think this UIS might not be related (I think my current problem is with Vue), so this issue might be some UIS <-> Flow issue?

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by dwsutherland** [comment]
Pretty clear what the issue is ... `workflow.id` is being returned as null/None.. just a matter of finding where this is happening..

**Comment by dwsutherland** [comment]
Fix up: https://github.com/cylc/cylc-flow/pull/4410
