### ISSUE TITLE
404 when going to "My Server" in the hub

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-uiserver#36]
With JupyterHub 1.0, it appears some change broke the link that used to work for "My Server" in the hub.

```
Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.7/site-packages/tornado/web.py", line 1676, in _execute
    result = self.prepare()
  File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.7/site-packages/tornado/web.py", line 2431, in prepare
    raise HTTPError(self._status_code)
tornado.web.HTTPError: HTTP 404: Not Found

```

**Comment by kinow** [comment]
Fixed in merged https://github.com/cylc/cylc-uiserver/pull/39, with another possible (simpler) solution in currently open https://github.com/cylc/cylc-uiserver/pull/40. Closing as issue fixed already in `master`.
