### ISSUE TITLE
Config arg error on hub launch

### ISSUE THREAD

**Issue by dwsutherland** [cylc/cylc-uiserver#385]
```
(uiserver) sutherlander@cortex-vBox:cylc-uiserver$ cylc hub
Traceback (most recent call last):
  File "/home/sutherlander/.envs/uiserver/bin/cylc", line 33, in <module>
    sys.exit(load_entry_point('cylc-flow', 'console_scripts', 'cylc')())
  File "/home/sutherlander/cylc/cylc-flow/cylc/flow/scripts/cylc.py", line 657, in main
    execute_cmd(command, *cmd_args)
  File "/home/sutherlander/cylc/cylc-flow/cylc/flow/scripts/cylc.py", line 284, in execute_cmd
    entry_point.resolve()(*args)
  File "/home/sutherlander/cylc/cylc-uiserver/cylc/uiserver/scripts/hub.py", line 41, in main
    hub_main(args)
  File "/home/sutherlander/.envs/uiserver/lib/python3.8/site-packages/jupyterhub/app.py", line 3307, in launch_instance
    loop.run_sync(self.launch_instance_async, argv)
  File "/home/sutherlander/.envs/uiserver/lib/python3.8/site-packages/tornado/ioloop.py", line 522, in run_sync
    timeout_handle = self.add_timeout(self.time() + timeout, timeout_callback)
TypeError: unsupported operand type(s) for +: 'float' and 'tuple'my 
```

**Release version(s) and/or repository branch(es) affected?**
```
(uis-test) sutherlander@cortex-vBox:~$ cylc --version
8.0.1
```
```
(uiserver) sutherlander@cortex-vBox:cylc-uiserver$ cylc --version
8.1.0.dev
(uiserver) sutherlander@cortex-vBox:cylc-uiserver$ git log
commit 549afbd99389a5e29571b3f5f71cc6e4505a4270 (HEAD -> master, origin/master, origin/HEAD)
.
.
.
(uiserver) sutherlander@cortex-vBox:cylc-flow$ git log
commit 277c7a51bb5f233c2f0e984e35e9aed83fd7787c (HEAD -> master, origin/master, origin/HEAD)
```

**Steps to reproduce the bug**
```
(uis-test) sutherlander@cortex-vBox:~$ history | tail -n 10
.
.
.
  143  mkvirtualenv uis-test
  144  pip install cylc-flow
  145  pip install cylc-uiserver
  146  cylc hub
  147  pip install jupyterhub>=1.4.0
  148  cylc hub
```
Or
```
(uiserver) sutherlander@cortex-vBox:cylc-uiserver$ python --version
Python 3.8.10
(uiserver) sutherlander@cortex-vBox:cylc-uiserver$ history | tail -n 25
  144  git clone https://github.com/cylc/cylc-uiserver.git
  145  cd cylc-uiserver/
.
.
.
  151  . ~/.envs/uiserver/bin/activate
  153  cd ../
  154  git clone https://github.com/cylc/cylc-flow.git
  155  cd cylc-flow/
  156  pip install -e .
  157  cd ../cylc-uiserver/
  158  pip install -e .[all]
  159  cylc hub
```

(no cylc hub/uis configuration on the machine)

**Expected behavior**
No error.

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by hjoliver** [comment]
The value of `timeout` in the traceback above is:
```
('--config=/home/oliverh/cylc/cylc-uiserver/venv/lib/python3.9/site-packages/cylc/uiserver/jupyterhub_confi                                                               
g.py',)
```
which, not surprisingly, causes a problem.

**Comment by hjoliver** [comment]
Downgrading jupyterhub from 3.0.0 to 2.3.1 makes the issue go away.

**Comment by hjoliver** [comment]
This looks like a bug in Jupyterhub, although I don't fully understand it yet.

version 2.3.1:
```python
3292     async def launch_instance_async(self, argv=None):                                                                                                                                     
3293         try:                                                                                                                                                                              
3294             await self.initialize(argv)                                                                                                                                                   
3295             await self.start()                                                                                                                                                            
3296         except Exception as e:                                                                                                                                                            
3297             self.log.exception("")                                                                                                                                                        
3298             self.exit(1)                                                                                                                                                                  
3299                                                                                                                                                                                           
3300     @classmethod                                                                                                                                                                          
3301     def launch_instance(cls, argv=None):                                                                                                                                                  
3302         self = cls.instance()                                                                                                                                                             
3303         self._init_asyncio_patch()                                                                                                                                                        
3304         loop = IOLoop.current()                                                                                                                                                           
3305         task = asyncio.ensure_future(self.launch_instance_async(argv))                                                                                                                    
3306         try:                                                                                                                                                                              
3307             loop.start()                                                                                                                                                                  
3308         except KeyboardInterrupt:                                                                                                                                                         
3309             print("\nInterrupted")                                                                                                                                                        
3310         finally:                                                                                                                                                                          
3311             if task.done():                                                                                                                                                               
3312                 # re-raise exceptions in launch_instance_async                                                                                                                            
3313                 task.result()                                                                                                                                                             
3314             loop.stop()                                                                                                                                                                   
3315             loop.close()              
```

Version 3.0.0:
```python
3292     async def launch_instance_async(self, argv=None):                                                                                                                                     
3293         try:                                                                                                                                                                              
3294             await self.initialize(argv)                                                                                                                                                   
3295             await self.start()                                                                                                                                                            
3296         except Exception as e:                                                                                                                                                            
3297             self.log.exception("")                                                                                                                                                        
3298             self.exit(1)                                                                                                                                                                  
3299                                                                                                                                                                                           
3300     @classmethod                                                                                                                                                                          
3301     def launch_instance(cls, argv=None):                                                                                                                                                  
3302         self = cls.instance()                                                                                                                                                             
3303         self._init_asyncio_patch()                                                                                                                                                        
3304         loop = IOLoop(make_current=False)                                                                                                                                                 
3305                                                                                                                                                                                           
3306         try:                                                                                                                                                                              
3307             loop.run_sync(self.launch_instance_async, argv)      # <---- ERROR HERE                                                                                                                          
3308         except Exception:                                                                                                                                                                 
3309             loop.close()                                                                                                                                                                  
3310             raise                                                                                                                                                                         
3311                                                                                                                                                                                           
3312         try:                                                                                                                                                                              
3313             loop.start()                                                                                                                                                                  
3314         except KeyboardInterrupt:                                                                                                                                                         
3315             print("\nInterrupted")                                                                                                                                                        
3316         finally:                                                                                                                                                                          
3317             loop.stop()                                                                                                                                                                   
3318             loop.close()        
```

The `argv` arg is the config file path It needs to be passed on to the arg list of `launch_instance_async` (which will read the config file before launching the instance) but it's now passed as the 2nd arg of `loop.run_sync` - which is supposed to be a timeout value.
