### ISSUE TITLE
FileNotFoundError including reference to old repo name

### ISSUE THREAD

**Issue by sadielbartholomew** [cylc/cylc-uiserver#41]
I am getting a traceback that seems to stem (at least partially) from a reference to the old repository name, ``cylc-web``:

```bash
Traceback (most recent call last):
  File "/home/h06/sbarth/miniconda3/envs/py3env/lib/python3.7/site-packages/tornado/web.py", line 1697, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/h06/sbarth/miniconda3/envs/py3env/lib/python3.7/site-packages/tornado/web.py", line 3174, in wrapper
    return method(self, *args, **kwargs)
  File "/net/home/h06/sbarth/cylc-uiserver/handlers.py", line 60, in get
    self.write(open(index).read())
FileNotFoundError: [Errno 2] No such file or directory: '/net/home/h06/sbarth/cylc-web/dist/index.html'
```

where by ``grep``ping for ``cylc-web`` I only see one hard-coded reference outside of the ``README.md`` file:

https://github.com/cylc/cylc-uiserver/blob/ef1ccd46f4fea465d324f2783ff32a55ca63612c/jupyterhub_config.py#L468-L471

so the issue must logically relate to that? Given this highly-probable origin, I would put in a "quick fix" PR, but from a little investigation, I am not sure if the final directory component of the path also needs amending, as there is no such ``dist/`` directory? There is an ``index.html`` file, as seems to be required given the traceback, under `` cylc-ui/public/`` (i.e. in the UI repository), but from reading that file it does not seem appropriate contextually. So while that could be the right place to point, I am not sure.

I've read through a lot of the comments in the ``jupyterhub_config.py`` file, but having just started looking at the UI & UI Server Cylc 8 components in development, I am not familiar enough yet to gain much help from them (along with some related docs reading), notably the one above the line in question. Therefore I thought it best to raise this as an Issue.

**Comment by sadielbartholomew** [comment]
This has since been solved by #43 (with clarification given in #40 for anyone following along.)
