### ISSUE TITLE
cylc.flow.exceptions.ClientError: could not read suite passphrase

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-uiserver#78]
Not sure if due to recent logging changes, now I am seeing the following exception:

```
[I 2019-09-16 16:44:26.306 JupyterHub log:174] 200 GET /hub/api/authorizations/token/[secret] (kinow@127.0.0.1) 26.79ms
2019-09-16 16:47:06,034 cylc.uiserver.data_mgr ERROR    could not read suite passphrase
Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.7/site-packages/cylc/flow/network/client.py", line 133, in async_request
    secret = self.secret()
  File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.7/site-packages/cylc/flow/network/authentication.py", line 41, in get_secret
    suite, content=True
  File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.7/site-packages/cylc/flow/suite_srv_files_mgr.py", line 311, in get_auth_item
    raise SuiteServiceFileError("Couldn't get %s" % item)
cylc.flow.exceptions.SuiteServiceFileError: Couldn't get passphrase

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/cylc-uiserver/cylc/uiserver/data_mgr.py", line 36, in get_workflow_data
    pb_msg = await client.async_request(method)
  File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.7/site-packages/cylc/flow/network/client.py", line 135, in async_request
    raise ClientError('could not read suite passphrase')
cylc.flow.exceptions.ClientError: could not read suite passphrase
2019-09-16 16:47:11,037 cylc.uiserver.data_mgr ERROR    could not read suite passphrase
Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.7/site-packages/cylc/flow/network/client.py", line 133, in async_request
    secret = self.secret()
  File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.7/site-packages/cylc/flow/network/authentication.py", line 41, in get_secret
    suite, content=True
  File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.7/site-packages/cylc/flow/suite_srv_files_mgr.py", line 311, in get_auth_item
    raise SuiteServiceFileError("Couldn't get %s" % item)
cylc.flow.exceptions.SuiteServiceFileError: Couldn't get passphrase

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/cylc-uiserver/cylc/uiserver/data_mgr.py", line 36, in get_workflow_data
    pb_msg = await client.async_request(method)
  File "/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.7/site-packages/cylc/flow/network/client.py", line 135, in async_request
    raise ClientError('could not read suite passphrase')
cylc.flow.exceptions.ClientError: could not read suite passphrase
```

Interestingly, I didn't get this at work today, only now at home. But perhaps I am using some old version. At home I have:

```
$ git log -n 1
commit affc0b8a6dab362cbcb42b1e9499ebcf5e38e6fd (HEAD -> master, upstream/master, upstream/HEAD, kinow/master)
Author: Bruno P. Kinoshita <bruno.kinoshita@niwa.co.nz>
Date:   Tue Sep 10 13:32:30 2019 +1200

    Use dictConfig with JSON instead of fileConfig with INI
```

Which is the latest commit.

**Comment by kinow** [comment]
More context: was running `cylc run --no-detach --verbose --debug five`, and `jupyterhub`. With the branch for the percent progress in Cylc UI. Didn't do anything extraordinary, just staring at the tree component looking for progress in some tasks.

**Comment by kinow** [comment]
Haven't seen this error in 0.3. Might have been fixed with our changes to auth and UIS/flow. Wen can still search closed issues later in case it happens again.
